#!/bin/zsh
DIR_ICLOUD=/Users/anderson/Library/Mobile\ Documents/com\~apple\~CloudDocs

while [ -z $LINK_WALLPAPER ]
do
  NUMBER=$(curl "https://www.random.org/integers/?num=1&min=1&max=890&col=1&base=10&format=plain&rnd=new" 2> /dev/null)
  LINK_WALLPAPER=$(grep -Eo "https://[a-zA-Z0-9./*/*/]*1920x1200.jpg" <<< \
    $(curl -L "https://pokewalls.wordpress.com/$NUMBER" 2> /dev/null) | sort --unique)
  NAME_POKEMON=$(sed -r 's#.*"species":\{"name":"?([^,"]*)"?.*#\1#' <<< \
    $(curl --location --request GET "https://pokeapi.co/api/v2/pokemon/$NUMBER" 2> /dev/null))
done

curl $LINK_WALLPAPER 2> /dev/null > $DIR_ICLOUD/Wallpaper/${NUMBER}${NAME_POKEMON}1920x1200.jpg
cp $DIR_ICLOUD/Wallpaper/${NUMBER}${NAME_POKEMON}1920x1200.jpg $DIR_ICLOUD/Wallpaper/obs_wallpaper.jpg
echo $NUMBER - $NAME_POKEMON
