[tools]
java = "oracle-graalvm-21"
lua = "5.1"
bun = "latest"
node = "22"
python = "3.12"
ruby = "3.2"
go = "1.25"
rust = { version = "1.83.0", profile = "minimal" }

# "npm:@zed-industries/vscode-langservers-extracted" = "latest"
"aqua:LuaLS/lua-language-server" = "3.17.1"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:bash-language-server" = "5.6.0"
"npm:@vtsls/language-server" = "0.3.0"
"npm:yaml-language-server" = "1.21.0"

# "go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"aqua:koalaman/shellcheck" = "0.11.0"
# "gem:ruby-lsp" = "latest"
"aqua:tamasfe/taplo" = "0.10.0"

"aqua:JohnnyMorganz/StyLua" = "2.4.0"
# "aqua:mvdan/sh" = "latest"
"npm:prettier" = "3.8.1"
"gem:rufo" = "0.18.2"

"npm:firecrawl-cli" = "latest"
"npm:@nshipster/sosumi" = "latest"
"npm:skills" = "1.4.6"
"npm:mcporter" = "0.8.1"

"npm:@anthropic-ai/sandbox-runtime" = "latest"
"npm:@anthropic-ai/claude-code" = "2.1.87"
"npm:@github/copilot" = "1.0.12"
"npm:opencode-ai" = "1.3.6"
"npm:@charmland/crush" = "0.53.0"
"npm:@google/gemini-cli" = "0.35.3"
"npm:@openai/codex" = "0.117.0"
"npm:@mariozechner/pi-coding-agent" = "latest"
"pipx:uv" = "0.11.2"
"pipx:frida-tools" = "14.8.0"
"npm:go-ios" = "1.0.188"
# "pipx:pymobiledevice3" = "latest"
# "pipx:frida-tools" = "latest"
# "pipx:yt-dlp" = "latest"

# "gem:rubocop" = "latest"
# "gem:fastlane" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true

# [settings.npm]
# package_manager = "bun"
